apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: rook-api
  labels:
    app: rook
spec:
  jobLabel: rook-api
  selector:
    matchLabels:
      app: rook-api
      rook_cluster: rook
  endpoints:
  - port: rook-api
    interval: 5s
