apiVersion: v1
kind: Service
metadata:
  name: prometheus-rook
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30200
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: rook
